### PR TITLE
Optimized PlayerData SQL table

### PR DESCRIPTION
**Pull request by castro12321**
- Added index on Player column
- Limited Player column length to 16 characters
- Added idea on how to let SQL maintain last update date

### CODE REVIEW

**Comment by caoli5288** [comment]
Let's test it.

**Comment by helptiger** [comment]
impossible to work because in the field Player the uuid is stored and not the playername!

**Comment by caoli5288** [comment]
> impossible to work because in the field Player the uuid is stored and not the playername!

You mean the index not work?

**Comment by castro12321** [comment]
Ouch didn't spot that. Anyway it's even better because you could replace varchar(16) to char(36). That's length of uuid

**Pull request merged**
